name: ldm
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11.4
- pip=23.1.2
- albumentations=1.3.1
- einops=0.6.1
- fire=0.5.0
- imageio=2.31.1
- imageio-ffmpeg=0.4.8
- ipython=8.14.0
- jupyterlab=4.0.2
- kornia=0.6.12
- numpy=1.25.0
- omegaconf=2.3.0
- pytorch=2.0.1
- pytorch-lightning=2.0.4
- streamlit=1.24.1
- torchmetrics=0.11.4
- torchvision=0.15.2
- transformers=4.28.1
- webdataset=0.2.48
- pip:
  - opencv-python==4.8.0.74
  - test-tube==0.7.5
  - open_clip_torch==2.20.0
  - invisible-watermark==0.2.0
  - streamlit-drawable-canvas==0.9.3
  - -e .
